# Generated by Django 5.1.2 on 2024-11-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the blog post', max_length=255)),
                ('description', models.TextField(help_text='The main content of the blog post')),
                ('tags', models.CharField(help_text='Comma-separated tags for the blog post', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the post was last updated')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
