# Generated by Django 5.1.2 on 2024-11-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name of the item', max_length=255)),
                ('item_desc', models.TextField(help_text='Detailed description of the item')),
                ('item_price', models.DecimalField(decimal_places=2, help_text='Price of the item (up to 10 digits with 2 decimal places)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the item was last updated')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
